In [28]:
from PublicDataReader import Ecos
service_key = "UQQE9TG8R51EYPTVJO2R"
api = Ecos(service_key)
df = api.get_statistic_table_list()
df[df['검색가능여부']=='Y'][48:58]

       상위통계표코드    통계표코드                             통계명 시점 검색가능여부    출처
71  0000000027  141Y009      1.2.3.6. 생명보험회사 지역별 여신(말잔)  M      Y  한국은행
72  0000000027  141Y005           1.2.3.7. 예금은행 지역별 연체율  M      Y  None
75  0000000036  151Y001        1.2.4.1.1. 가계신용(업권별, 분기)  Q      Y  None
76  0000000036  151Y004        1.2.4.1.2. 가계신용(용도별, 분기)  Q      Y  None
78  0000000037  151Y002  1.2.4.2.1. 예금취급기관 가계대출(업권별, 월)  M      Y  None
79  0000000037  151Y005  1.2.4.2.2. 예금취급기관 가계대출(용도별, 월)  M      Y  None
82  0000000039  131Y016  1.2.5.1.1. 산업별대출금(예금취급기관, 전산업)  Q      Y  None
83  0000000039  131Y017  1.2.5.1.2. 산업별대출금(예금취급기관, 용도별)  Q      Y  None
85  0000000040  131Y013    1.2.5.2.1. 산업별대출금(예금은행, 전산업)  Q      Y  None
86  0000000040  131Y011    1.2.5.2.2. 산업별대출금(예금은행, 용도별)  Q      Y  None

In [30]:
df = api.get_statistic_item_list(통계표코드="141Y005")
df

,통계표코드,통계명,항목그룹코드,항목그룹명,통계항목코드,통계항목명,상위통계항목코드,상위통계항목명,시점,수록시작일자,수록종료일자,자료수,단위,가중치
0,141Y005,1.2.3.7. 예금은행 지역별 연체율,Group1,계정항목,R8AB00,원화대출금연체율(전체1M),None,None,A,2019,2022,100,%,None
1,141Y005,1.2.3.7. 예금은행 지역별 연체율,Group1,계정항목,R8AB00,원화대출금연체율(전체1M),None,None,M,201912,202310,1168,%,None
2,141Y005,1.2.3.7. 예금은행 지역별 연체율,Group1,계정항목,R8AB00,원화대출금연체율(전체1M),None,None,Q,2019Q4,2023Q3,393,%,None
3,141Y005,1.2.3.7. 예금은행 지역별 연체율,Group1,계정항목,R5AB00,가계대출 연체율(전체1M),R8AB00,원화대출금연체율(전체1M),A,2019,2022,100,%,None
4,141Y005,1.2.3.7. 예금은행 지역별 연체율,Group1,계정항목,R5AB00,가계대출 연체율(전체1M),R8AB00,원화대출금연체율(전체1M),M,201912,202310,1168,%,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
70,141Y005,1.2.3.7. 예금은행 지역별 연체율,Group2,지역코드,H00,세종,None,None,M,201912,202310,558,None,None
71,141Y005,1.2.3.7. 예금은행 지역별 연체율,Group2,지역코드,H00,세종,None,None,Q,2019Q4,2023Q3,186,None,None
72,141Y005,1.2.3.7. 예금은행 지역별 연체율,Group3,보고기관,0960,국내은행(수출입은행 포함),None,None,A,2019,2022,600,None,None
73,141Y005,1.2.3.7. 예금은행 지역별 연체율,Group3,보고기관,0960,국내은행(수출입은행 포함),None,None,M,201912,202310,7008,None,None
74,141Y005,1.2.3.7. 예금은행 지역별 연체율,Group3,보고기관,0960,국내은행(수출입은행 포함),None,None,Q,2019Q4,2023Q3,2358,None,None

In [67]:
df = api.get_statistic_search(통계표코드="141Y005", 통계항목코드1='R4AB00', 주기='Q', 검색시작일자='2019Q4',검색종료일자='2023Q3').groupby(['통계항목명2','시점'])
df['값'].sum()

통계항목명2  시점
강원      2019Q4    0.13
        2020Q1    0.22
        2020Q2    0.12
        2020Q3    0.17
        2020Q4    0.13
                  ...
충북      2022Q3    0.13
        2022Q4    0.15
        2023Q1    0.19
        2023Q2    0.17
        2023Q3    0.19
Name: 값, Length: 288, dtype: object

In [10]:
df = api.get_statistic_search(통계표코드="200Y001", 주기="A", 검색시작일자="2015", 검색종료일자="2021")
df.head()

,통계표코드,통계명,통계항목코드1,통계항목명1,통계항목코드2,통계항목명2,통계항목코드3,통계항목명3,통계항목코드4,통계항목명4,단위,WGT,시점,값
0,200Y001,2.1.1.1. 주요지표(연간지표),10101,"국내총생산(명목, 원화표시)",None,None,None,None,None,None,십억원,None,2015,1658020.4
1,200Y001,2.1.1.1. 주요지표(연간지표),10101,"국내총생산(명목, 원화표시)",None,None,None,None,None,None,십억원,None,2016,1740779.6
2,200Y001,2.1.1.1. 주요지표(연간지표),10101,"국내총생산(명목, 원화표시)",None,None,None,None,None,None,십억원,None,2017,1835698.2
3,200Y001,2.1.1.1. 주요지표(연간지표),10101,"국내총생산(명목, 원화표시)",None,None,None,None,None,None,십억원,None,2018,1898192.6
4,200Y001,2.1.1.1. 주요지표(연간지표),10101,"국내총생산(명목, 원화표시)",None,None,None,None,None,None,십억원,None,2019,1924498.1

In [11]:
df = api.get_key_statistic_list()
df.head()

  통계그룹명            통계명      값        시점  단위
0  시장금리      한국은행 기준금리    3.5  20240113  %
1  시장금리       콜금리(익일물)  3.473  20240115  %
2  시장금리   KORIBOR(3개월)   3.68  20240115  %
3  시장금리     CD수익률(91일)   3.74  20240115  %
4  시장금리  통안증권수익률(364일)  3.284  20240115  %